-- Creating inventory table to store certain data `inventory`
CREATE TABLE public.inventory(
	inv_id INT GENERATED BY DEFAULT AS IDENTITY,
	inv_make CHARACTER VARYING  NOT NULL,
	inv_model CHARACTER VARYING  NOT NULL,
	inv_year CHARACTER (4)   NOT NULL,
	inv_description CHARACTER VARYING NOT NULL,
	inv_image CHARACTER VARYING  NOT NULL,
	inv_thumbnail CHARACTER VARYING NOT NULL,
	inv_price NUMERIC(9,0) NOT NULL,
	inv_miles INTEGER NOT NULL,
	inv_color CHARACTER VARYING  NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
	
)